namespace EasyIntercept.Hosting;

/// <summary>
/// The markdown served at <c>/llms.txt</c>: everything a coding agent on this machine needs to
/// route traffic through the proxy, read the captured session files, write mock rules and call
/// the API. Rendered by the running instance so ports and folders are the real ones.
/// Pass <c>paths = null</c> for callers that are not on loopback; folder paths are then omitted.
/// </summary>
public static class AgentGuide
{
    private const string NotShown =
        "(not shown: this request did not come from loopback. Ask the user on the machine where EasyIntercept runs)";

    public static string Render(int uiPort, AppPaths? paths)
    {
        var ui = $"http://localhost:{uiPort}";
        var proxy = $"http://127.0.0.1:{StartupOptions.ProxyPort}";
        var sessionsDir = paths?.Sessions ?? NotShown;
        var rulesDir = paths?.AutoResponder ?? NotShown;
        var dataRoot = paths?.Root ?? NotShown;

        return $$"""
            # EasyIntercept: guide for coding agents

            EasyIntercept is a local HTTP/HTTPS debugging proxy running on this machine. It records every
            request/response that passes through it as a JSON file you can read, lets you mock responses
            with rule files, and understands LLM API traffic (OpenAI, Anthropic, Gemini, GitHub Copilot).
            This page is generated by the running instance, so the ports and folders below are the real ones.

            ## Is it running?

            - Web UI and API: {{ui}} (`curl {{ui}}/api/info` returns `{"version":"…","uiPort":{{uiPort}},"proxyPort":{{StartupOptions.ProxyPort}},"agentGuide":"/llms.txt","openApi":"/openapi/v1.json"}`)
            - Proxy: {{proxy}} (plain HTTP and HTTPS via CONNECT; this port is fixed)
            - OpenAPI document: {{ui}}/openapi/v1.json (machine-readable description of the API endpoints listed at the bottom of this page)

            ## Route traffic through the proxy

            Pick one:

            1. **Per process**: set `HTTP_PROXY={{proxy}}` and `HTTPS_PROXY={{proxy}}`. Honoured by curl,
               Python (requests, httpx), .NET HttpClient, Go, pip, and Node when started with `NODE_USE_ENV_PROXY=1`
               (or use an undici `ProxyAgent`). One-off: `curl -x {{proxy}} https://example.com`.
            2. **Whole machine**: `curl -X POST {{ui}}/api/system-proxy -H "Content-Type: application/json" -d '{"enabled":true}'`
               flips the OS proxy setting (send `false` to undo; `GET {{ui}}/api/system-proxy` shows the state).
            3. **A browser**: `curl -X POST {{ui}}/api/browser-launch -H "Content-Type: application/json" -d '{"browserId":"chrome"}'`
               starts an isolated Chrome profile whose traffic (and only its traffic) goes through the proxy.
               `GET {{ui}}/api/browser-launch` lists the browsers found.

            **HTTPS** is re-signed with EasyIntercept's own root CA. Fetch it with `curl -o easyintercept-ca.crt {{ui}}/ca`
            (PEM) and trust it for the tool you use: curl `--cacert easyintercept-ca.crt`, Node `NODE_EXTRA_CA_CERTS=easyintercept-ca.crt`,
            Python `REQUESTS_CA_BUNDLE=easyintercept-ca.crt` or `SSL_CERT_FILE=…`. Or trust it system-wide
            (Windows: the installer task or `EasyIntercept.exe --install-ca`; macOS: `install-ca.sh`).
            Hosts that pin their certificate cannot be intercepted; expect TLS errors for those.

            Quick check that capture works:

            ```
            curl -s -x {{proxy}} --cacert easyintercept-ca.crt https://httpbin.org/get
            curl -s {{ui}}/api/sessions | head -c 400
            ```

            ## Session files (what was captured)

            Folder: `{{sessionsDir}}`

            One file per request, named `NNNN_METHOD_host_path.json`, for example
            `0042_POST_api.openai.com_v1_chat_completions.json`. `NNNN` increases in capture order, so the
            highest number is the newest. At most 1000 files are kept; the oldest are deleted automatically.

            Field names **on disk are PascalCase**; the API returns the same fields in **camelCase**.

            ```json
            {
              "Id": "b0c1d2e3-…",                        // GUID, used by the /api/sessions/{id}/… endpoints
              "Timestamp": "2026-09-07T10:15:52.123Z",   // UTC, when the request started
              "Method": "POST",
              "Url": "https://api.openai.com/v1/chat/completions",
              "RequestHeaders": { "Content-Type": "application/json", "Authorization": "Bearer <redacted here; real files hold the actual token>" },
              "RequestBody": "{\"model\":\"gpt-5.4\",…}",   // a string; parse it again to get the JSON
              "ResponseStatus": 200,                     // 0 = still in flight
              "ResponseHeaders": { "Content-Type": "application/json" },
              "ResponseBody": "{\"id\":\"chatcmpl-…\",…}",   // a string
              "DurationMs": 912
            }
            ```

            How bodies are stored:

            - Text bodies (content type containing `text/`, `json`, `xml`, `javascript` or
              `x-www-form-urlencoded`; responses of 4 KB or less always) are stored verbatim as text.
              A JSON body is therefore a JSON string containing JSON: decode twice.
            - Streaming responses (`text/event-stream`) are stored raw, event lines included; the UI
              reconstructs them into one message, the file does not.
            - Images up to 5 MB become a `data:<type>;base64,…` URL. Other binary bodies are replaced by
              a placeholder such as `[12345 bytes]` or `[123 bytes binary]`.
            - A response served by a mock rule carries the header `X-EasyIntercept-AutoResponder: true`.
            - **Session files contain secrets.** Headers and bodies are stored verbatim: Authorization headers,
              cookies, API keys, personal data. Treat every file as confidential; never paste its contents into
              a chat, commit, issue or log, and quote only what the task needs.

            Recipes:

            - Newest capture: the highest-numbered file, or the first element of `GET {{ui}}/api/sessions` (newest first).
            - Every call to one host: `grep -l "api.openai.com" *.json` inside the sessions folder.
            - File path for a session id: `GET {{ui}}/api/sessions/{id}/file-path` returns `{"path":"…"}`.
            - Re-send a captured request: `POST {{ui}}/api/sessions/{id}/replay` returns `{"status":200,"body":"…"}`.
              The replay goes through the proxy again, so it is captured and can be mocked like the original.
            - Delete some: `POST {{ui}}/api/sessions/delete` with a JSON array of ids. Delete all: `DELETE {{ui}}/api/sessions`.
            - Reveal the file in Windows Explorer for the user (Windows only): `POST {{ui}}/api/sessions/{id}/show-in-explorer`.
            - Export to Bruno: `POST {{ui}}/api/bruno/export` with `{"sessionIds":["…"],"collectionPath":"/absolute/folder","name":"optional"}`.

            ## Mock responses (Auto Responder)

            Folder: `{{rulesDir}}`

            Drop a JSON file in that folder (any file name) and it is live within about half a second, no
            restart needed. Files the app writes itself are named `METHOD_host_path.json`. The first enabled
            rule that matches wins; matching is exact on method and URL (query string included), optionally
            narrowed by the request body.

            ```json
            {
              "Id": "3f9c2c0e-5d3a-4b7e-9a1e-7c2f1d0b8e21",
              "Name": "Orders API: force an empty list",
              "IsEnabled": true,
              "Method": "GET",
              "Url": "https://api.example.com/orders?status=open",
              "ResponseStatus": 200,
              "ResponseHeaders": { "Content-Type": "application/json" },
              "ResponseBody": "{\"orders\":[]}",
              "LatencyMs": 250,
              "BodyMatchType": "none",
              "BodyMatch": ""
            }
            ```

            - `Id`: any GUID, unique per rule (generate one). `LatencyMs` delays the reply.
            - `BodyMatchType`: `none`, `contains` (case-insensitive substring of the request body) or `regex` (.NET syntax).
              Use it to give two requests to the same URL different answers.
            - The same via the API, in camelCase: `GET/POST {{ui}}/api/auto-responders`,
              `PUT {{ui}}/api/auto-responders/{id}` (body must carry the same id), `DELETE {{ui}}/api/auto-responders/{id}`.
            - To mock a real answer, copy `ResponseHeaders` and `ResponseBody` from a captured session file and edit the body.

            ## API summary

            | Method | Path | Purpose |
            |---|---|---|
            | GET | `/llms.txt` | This page |
            | GET | `/openapi/v1.json` | OpenAPI 3 description of this API, for tooling that wants a machine-readable spec |
            | GET | `/api/info` | Version and ports |
            | GET | `/api/sessions` | All captured sessions, newest first (camelCase) |
            | DELETE | `/api/sessions` | Delete all sessions and their files |
            | POST | `/api/sessions/delete` | Delete the sessions whose ids are in the JSON array body |
            | POST | `/api/sessions/{id}/replay` | Re-send a captured request through the proxy |
            | GET | `/api/sessions/{id}/file-path` | Absolute path of the session's JSON file |
            | POST | `/api/sessions/{id}/show-in-explorer` | Reveal that file in Windows Explorer (Windows only) |
            | POST | `/api/bruno/export` | Write sessions as `.bru` files into a Bruno collection folder |
            | GET / POST | `/api/auto-responders` | List / create mock rules |
            | PUT / DELETE | `/api/auto-responders/{id}` | Update / delete a mock rule |
            | GET / POST | `/api/system-proxy` | Read / set the OS-level proxy setting (`{"enabled":bool}`) |
            | GET / POST | `/api/browser-launch` | List browsers / launch an isolated proxied browser (`{"browserId":"chrome"}`) |
            | GET | `/ca` | The root CA certificate (PEM) |
            | GET | `/install` | Human-facing page with a QR code to install the CA on a phone |

            Realtime: the UI listens on a SignalR hub at `/proxy-hub` (events `NewSession`, `UpdateSession`).
            For an agent, polling `GET /api/sessions` or watching the sessions folder is simpler.

            ## Things to know

            - The UI port is configurable (this instance: {{uiPort}}); the proxy port {{StartupOptions.ProxyPort}} is not.
            - Only one instance runs per machine; starting a second one just opens the UI of the first.
            - Everything lives under `{{dataRoot}}` (override with the `DataRoot` setting) as plain files you may read, grep and edit.
            - Folder paths on this page are filled in only for requests coming from the machine itself (loopback).
            """;
    }
}
